AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Globals:
  Function:
    MemorySize: 128
    Architectures: ["arm64"]
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 5
    Tracing: Active

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{id}
            Method: GET
    Metadata:
      BuildMethod: makefile

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"